### ISSUE TITLE
tailwind v3: Breaks all other grid types

### ISSUE THREAD

**Issue by busybox11** [SavvyWombat/tailwindcss-grid-areas#3]
Hi,
First of all, thanks for this awesome module, it helped me build a complex grid layout so easily, compared to tailwind's built in grid functionnality.
I've got a problem with it though.
When i use this module, all other grid properties are not built by PostCSS, but if I remove the module from tailwind's configuration, they are.
Is it possible to fix this behavior in order to have both the module's properties and tailwind's compiled to the output style?
I'm going to try to fix it by myself in parallel, this issue is here so that you're aware of this behavior.

**Comment by horuskol** [comment]
Hi, thanks for taking the time to let me know about this behaviour - I'll be sure to take a look.

Could you provide a couple of examples of the core grid properties that are being excluded, so I can investigate?

I'll also happily review and accept a pull request if you do come up with a fix in the meantime.

**Comment by busybox11** [comment]
Thank you!

Sure thing.
After some troubleshooting, we found out when `gridTemplateColumns` is commented in the config file, it works as expected.
![image](https://user-images.githubusercontent.com/29630035/165385148-73cf2f7b-536c-40fc-a281-fee760531e93.png)
![image](https://user-images.githubusercontent.com/29630035/165385160-37bbad94-9134-4867-9c5c-dba4b1b54140.png)

Though, if you put  `gridTemplateColumns` in the `extend` section of Tailwind's config file, all the grids item are generated, plus the module's ones, because this is a Tailwind property name.
![image](https://user-images.githubusercontent.com/29630035/165385355-3cbbc642-5ab9-434d-891a-5bd5da0fe170.png)

That was not specified in the documentation and thus using the same config file structure removed the default config.
Maybe this should be specified. What is sure though is that no change to the module is required, this is only a misunderstanding from me. The module works fine :)

Thanks again!

**Comment by horuskol** [comment]
Thanks very much for coming back with the extra information and for letting me know the issue with my documentation. I'll get that fixed today.
