### ISSUE TITLE
Custom property arbitrary values incorrectly wrapped in quotes

### ISSUE THREAD

**Issue by joeldbirch** [SavvyWombat/tailwindcss-grid-areas#4]
Hello, and thanks for your great work on this plugin. I need to generate complex grids on the fly using arbitrary values, so this plugin takes Tailwind a step closer to being a viable replacement for my current utility class library (Hucssley).

However, I need to be able to use custom properties in arbitrary value classes, which works for Tailwind's official classes, but there's one hopefully minor issue preventing it from working for `grid-areas`. Please see my two attached screenshots of the Tailwind Playground configured to use your grid-areas plugin.

As you can see from Image 1, Tailwind's `grid-rows` class generates the expected CSS value containing a working custom property, while Image 2 shows that the grid-areas plugin is wrapping quotes around the custom property, causing it not to work.

| Image 1 | Image 2 |
|---------|---------|
|   <img width="1137" alt="Screen Shot 2023-01-28 at 2 47 16 pm" src="https://user-images.githubusercontent.com/75602/215241060-2650b067-0164-46af-b84c-00c71a8674e2.png">        |         <img width="1137" alt="Screen Shot 2023-01-28 at 2 46 25 pm" src="https://user-images.githubusercontent.com/75602/215241071-f4606a9a-48ae-45ec-8d82-bf58d7ba601b.png">    |

Is this a bug, and/or is there a workaround I should be using, please? Thanks for your time.

**Comment by peteakhurst** [comment]
+1 for understanding this bug/work around also

**Comment by horuskol** [comment]
Hi - thanks for reporting this issue. Yeah, it's a big - I hadn't thought about using custom properties in arbitrary values. Shouldn't be too hard to resolve when I have a spare moment tomorrow.

**Comment by horuskol** [comment]
Just released [3.0.1](https://github.com/SavvyWombat/tailwindcss-grid-areas/releases/tag/3.0.1) which should resolve the problem. Thanks for the feedback.

**Comment by joeldbirch** [comment]
Thanks so much! Looking forward to trying it out.

**Comment by horuskol** [comment]
As a fix was released and there's been no further activity, I'm closing this issue. Thanks again.
