### ISSUE TITLE
I cannot unset the grid area

### ISSUE THREAD

**Issue by martinharyanto** [SavvyWombat/tailwindcss-grid-areas#5]
I sit possible to have property for `grid-area-unset`, `grid-area-auto`, etc?
I would like to be able to unset it when using container query from tailwind. 

```
 <div className={clsx(
       'grid grid-areas-myarea',
       '@[680px]/table:grid-cols-5 @[680px]/table:items-center' // I want to add @[680px]/table:grid-areas-unset or something like that to reset
   )}
>
```

I think it would be nice if it will generate also those "reset" classes for us when we add this plugin to tailwind.
Also the "reset" class for the child that have `grid-in-left` or `grid-in-right` should be able to be resetted?

**Comment by horuskol** [comment]
Hi, thanks for the suggestion.

I'll look into adding utilities for CSS keyword/global values like `grid-template-areas: none` and `grid-area: auto`, etc, and get a release out in the next week or so.

**Comment by horuskol** [comment]
I've added the following utilities to the plugin:

```
grid-areas-none
grid-areas-inherit
grid-areas-initial
grid-areas-revert
grid-areas-revert-layer
grid-areas-unset

grid-in-auto
grid-in-inherit
grid-in-initial
grid-in-revert
grid-in-revert-layer
grid-in-unset
```
