### ISSUE TITLE
Not able to use default tailwind custom grid template

### ISSUE THREAD

**Issue by martinharyanto** [SavvyWombat/tailwindcss-grid-areas#6]
Hi, I found a bug when using this plugin for tailwind.

I tried to make an element that have class `grid-cols-[1fr_120px]` and it is nor working.
I tried to remove the plugin from `tailwind.config.js` and the class was working fine.

I was curious so i tried multiple classes, and found out:

 - doing px first for the template column with only 2 values, still works fine:
     - `grid-cols-[120px_1fr]` is working fine ✅ 
     - `grid-cols-2` is working fine ✅ 
 - doing anything other than first rule, breaks the tailwind grid (is not applying any css on the browser ❌ ):
     - `grid-cols-[120px_120px_120px]` -  ❌ 
     - `grid-cols-[minmax(100px,120px)_1fr]`-  ❌ 
     - `grid-cols-[1fr_120px] - ❌ 
     - `grid-cols-3` - ❌ 

Not sure what happens, but can you checked on it?
I am very sorry that I can't reproduce it anywhere as I dont understand where to put the code with tailwind installed, etc..
I hope this can be fixed soon 👍 

_Edit_:
Upon looking at issues reported by previous githubers, I saw that someone also got this problem. But I still can't figure out what was the problem, and how to fix it. Should I not add `gridTemplateColumns` on `extend` property?

This is my tailwind.config file if it helps

<img width="677" alt="image" src="https://github.com/SavvyWombat/tailwindcss-grid-areas/assets/102503831/b032559a-f367-4913-98eb-517364c8a83f">

**Comment by horuskol** [comment]
Hi, thanks for taking the time to write this up and include various passing and failing examples. I'll take a look and see what I can do to resolve this over the next few days.

**Comment by horuskol** [comment]
I'm afraid I don't seem to be able to replicate the issue - I've even tried to create a failing test base on some of your configuration and examples https://github.com/SavvyWombat/tailwindcss-grid-areas/blob/main/test/css.test.js

Could you paste your whole config as text?
Also, please can you confirm what version of Tailwind you are using?

**Comment by martinharyanto** [comment]
Hi sorry for late reply on this matter, I really didn't get to open my mail since I am very busy on work for several weeks..
This is my package.json
```
    "tailwindcss": "3.3.2",
    "@savvywombat/tailwindcss-grid-areas": "^3.0.1",
    "next": "13.3.1",
    "typescript": "5.0.4",
    "@tailwindcss/container-queries": "^0.1.1",
    ....
```

Also, I re-tried all of the failing cases before, and it comes out, it doesn't happen anymore.
I think probably I was installing and not restarting the project just to make sure it doesn't have styling cache.
Thanks for the check and clarification 🙏
